apiVersion: security.policy.gloo.solo.io/v2
kind: WAFPolicy
metadata:
  annotations:
    cluster.solo.io/cluster: ""
  name: break-some-waf
  namespace: default
spec:
  applyToRoutes:
  - route:
      labels:
        route: httpbin
  config:
    customInterventionMessage: 'ModSecurity intervention! Custom message details here..'
    customRuleSets:
    - ruleStr: |
        # Turn rule engine on
        SecRuleEngine On
        # Note the /0 in the CIDR that causes the issue on Envoy.
        # SecRule REMOTE_ADDR "!@ipMatch 10.244.0.0/24" "phase:1,deny,status:403,id:1,msg:'block ip'"
        SecRule REMOTE_ADDR "!@ipMatch 10.244.0.0/0" "phase:1,deny,status:403,id:1,msg:'block ip'"
    disableCoreRuleSet: true
    priority: 0