apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: api-example-com-rt
  namespace: gloo-mesh-gateways
spec:
  hosts:
  - api.example.com
  virtualGateways:
  - name: istio-ingressgateway
    namespace: gloo-mesh-gateways
  http:
  - name: httpbin
    labels:
      route: "httpbin"
    matchers:
    - uri:
        prefix: /httpbin
    forwardTo:
      pathRewrite: /
      destinations:
      - ref:
          name: httpbin
          namespace: default
        port:
          number: 8000